### ISSUE TITLE
4 Files

### ISSUE THREAD

**Issue by bricktale** [ardaozkal/ownshot#6]
I have made it like in the wiki, but there arnt files like serverlink.txt.
Need Help pls

**Comment by aveao** [comment]
Hello, sorry for the wait.

Please create those files if they don't exist.

I'll make sure to include a configuration helper app in the next version.

**Comment by aveao** [comment]
As I didn't get any response from you, I guess this solved your issue. I'm closing this issue, but feel free to reopen if this didn't fix your issue.
